dist: xenial
language: clojure
node_js:
- '11'
script: lein doo node "server-tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
before_install:
  - sudo add-apt-repository --yes ppa:ethereum/ethereum
  - sudo apt-get -qq update
before_script:
  - nvm use 11.0.0
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo npm install -g truffle
  - npm install -g ganache-cli
  - ganache-cli -p 8549 -l 80000000 --allowUnlimitedContractSize -d -m district0x > /dev/null &
  - truffle migrate --network ganache --f 2 --to 3
env:
  global:
  - secure: Nio+lEZzY5Kdn5Z7UUScZwPrdUOZgv1GfvE4u9W5+2mmnckdMLtmtxhOd/vM4oPXqHbckYsC9DKBgwvZKQ18laZEQpzyNGXMjjDMAuHtpCv3m8MBJQ/tFJDUyig1PnqSSml2bMtKsrj6tjJZUkp57vLiErcrRabwAxYe+TpeV7AXq80IQUnuQf4g2lcseK3yMN9HQou0jrZubctO1erF5ncOagXtA/YXEST03YxP3s4o1eF2SfqASbpdPREQ+16ieqRar9ny8JkdshdPuVj+5iC5IALEKIrKUiWqQ+ibiepmLjItg+1RGoIW6Fwjon0Ej+d8WGLyjGTMWB8ZVWQ5loYjntJ/HYo75KV8bn/mp/l6awQAia41bV8A3hpGQ8MCa1Y5XIE+SlK3XXfHN7V4Ifc3DR7au0ZQC7jO/aJeS3Q7vg2NXOoan0AiDDfwAayau8DZZ4M7ssj2Rh8aH44ca6dpZQA1TGuLbFGfMd9jNpyTujcb12JlCYvx2fw8lvM2aYycy4GbmOT2fP3658xvzpQY0EFTPtOizztVzz07KgjPmC9/7cC9yl+lssZCpyrkLWc1sLkdjpkXJMQwefdgoItW92yc/qlWJSZKJwpgtOMbcGvt1sp4OAg1IGbyWqnqhbLbs4wY3jmjw9O7fFDgDlnnIuMD1Stcp7dXGsnlSd8=
  - secure: 16e8bSvJRP6tKT51snJRrXnPX3sw7lMpD/IHs+5YM7JPqin1iu7koJjjYPT+WDEq6+W7Eng6Yk/uy+JO5aCt0DM8BI2wfgEG3yTsdIZGQkIkyjhVJgqS/vvEgBJ4Ox1HlEP9DyCQc8mUOCB2lTGenxTjQN1mpOyVXq/HXZ+pfAE6P6ihuKgvKEzg+x3gLj2MPYQnyWXBdGHSXfRJOZPCGufaQsTVXWsi+oZwtmirWP0j5GnSNcDV2bILl/lh2+NVIP8knBWMrrZ/NfzmcHIEbQ1YXgqVvKvNux7mh0RJc8Z8ynHVLVDpjlqaBnCzxw4N5TAey+ofKZ6YOMiMomLaZrPljpQEaRrZdpt63D2ENKHKDy4caxFLIruhKxbQBWZFP+uysNToOyySLudWsNRZyN3qX94eiJ9Nz5o3WhyHZ86kAFZCE+KRVTCjULPfMbRk2xFlWM4Wti6jLw03QPE57LnelyUlMTjGI4Nsv3zLHBO6LiRjXH8F+XSOya3rnZZzkjgRmY+ZQlfmI4Y10pfKvo5OCPn3lbB8vihYUxjLxo9xnoztV1WYWQRu5VhY+b/HN4siAsaDXWUfQosNjzZkok5Oue8PgZjoR63KXmHnnm7/YFXv/CDvxLY5oiHrsRHdR8RTzZ+s5OwFnljAIOaaLy1oU2OeAlOBSSZXRbuXKgg=
services:
  - docker
deploy:
- provider: script
  script: bash docker-push.sh qa
  on:
    branch: master
